<a target="_blank" href="https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/vci/vci_functions_demo.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# M·ª•c l·ª•c

# I. C√†i ƒë·∫∑t

## C√†i ƒë·∫∑t th∆∞ vi·ªán

In [ ]:
!pip install -U vnstock

## N·∫°p th∆∞ vi·ªán l·∫ßn ƒë·∫ßu

> B·∫°n c√≥ th·ªÉ n·∫°p to√†n b·ªô c√°c module c·ªßa th∆∞ vi·ªán v√†o m√¥i tr∆∞·ªùng l√†m vi·ªác n·∫øu ch∆∞a bi·∫øt r√µ m√¨nh c·∫ßn g√¨ ho·∫∑c ch·ªçn t·ª´ng module ri√™ng bi·ªát ƒë·ªÉ n·∫°p v√†o khi ƒë√£ quen thu·ªôc.

In [1]:
from vnstock.explorer.vci import Listing, Quote, Company, Finance, Trading

# II. Truy xu·∫•t d·ªØ li·ªáu - CK Vi·ªát Nam

## Listing: Li·ªát k√™ danh s√°ch ch·ª©ng kho√°n

In [2]:
listing = Listing()

### Danh s√°ch t·∫•t c·∫£ m√£ CK ni√™m y·∫øt (ƒë∆°n gi·∫£n)

In [3]:
# VCI l√† ngu·ªìn d·ªØ li·ªáu t·ª´ CK Vietcap b√™n c·∫°nh ngu·ªìn t·ª´ TCBS
listing.all_symbols()

     symbol                                         organ_name
0       YTC  C√¥ng ty C·ªï ph·∫ßn Xu·∫•t nh·∫≠p kh·∫©u Y t·∫ø Th√†nh ph·ªë ...
1       YEG                     C√¥ng ty C·ªï ph·∫ßn T·∫≠p ƒëo√†n Yeah1
2       YBM     C√¥ng ty C·ªï ph·∫ßn Kho√°ng s·∫£n C√¥ng nghi·ªáp Y√™n B√°i
3       YBC      C√¥ng ty C·ªï ph·∫ßn Xi mƒÉng v√† Kho√°ng s·∫£n Y√™n B√°i
4       XPH                    C√¥ng ty C·ªï ph·∫ßn X√† ph√≤ng H√† N·ªôi
...     ...                                                ...
1708    AAS            C√¥ng ty C·ªï ph·∫ßn Ch·ª©ng kho√°n SmartInvest
1709    AAM                    C√¥ng ty C·ªï Ph·∫ßn Th·ªßy S·∫£n MeKong
1710    AAH                           C√¥ng ty C·ªï ph·∫ßn H·ª£p Nh·∫•t
1711    AAA                  C√¥ng ty C·ªï ph·∫ßn Nh·ª±a An Ph√°t Xanh
1712    A32                                 C√¥ng ty C·ªï ph·∫ßn 32

[1713 rows x 2 columns]

In [5]:
# # Xu·∫•t d·ªØ li·ªáu ra file csv
# listing.all_symbols().to_csv('assets/data/all_symbols.csv', index=False)

### Li·ªát k√™ m√£ CP theo s√†n (ƒë·∫ßy ƒë·ªß)

In [6]:
# D·ªØ li·ªáu bao g·ªìm t·∫•t c·∫£ c√°c m√£ kh√¥ng k·ªÉ ƒëang ni√™m y·∫øt hay kh√¥ng
listing.symbols_by_exchange()

,symbol,exchange,type,organ_short_name,organ_name,product_grp_id
0,YTC,UPCOM,STOCK,XNK Y t·∫ø TP.HCM,C√¥ng ty C·ªï ph·∫ßn Xu·∫•t nh·∫≠p kh·∫©u Y t·∫ø Th√†nh ph·ªë ...,UPX
1,YEG,HSX,STOCK,T·∫≠p ƒëo√†n Yeah1,C√¥ng ty C·ªï ph·∫ßn T·∫≠p ƒëo√†n Yeah1,STO
2,YBM,HSX,STOCK,Kho√°ng s·∫£n CN Y√™n B√°i,C√¥ng ty C·ªï ph·∫ßn Kho√°ng s·∫£n C√¥ng nghi·ªáp Y√™n B√°i,STO
3,YBC,UPCOM,STOCK,Xi mƒÉng v√† Kho√°ng s·∫£n Y√™n B√°i,C√¥ng ty C·ªï ph·∫ßn Xi mƒÉng v√† Kho√°ng s·∫£n Y√™n B√°i,UPX
4,XPH,UPCOM,STOCK,X√† ph√≤ng H√† N·ªôi,C√¥ng ty C·ªï ph·∫ßn X√† ph√≤ng H√† N·ªôi,UPX
...,...,...,...,...,...,...
2856,AAM,HSX,STOCK,Th·ªßy s·∫£n Mekong,C√¥ng ty C·ªï Ph·∫ßn Th·ªßy S·∫£n MeKong,STO
2857,AAH,UPCOM,STOCK,Than H·ª£p Nh·∫•t,C√¥ng ty C·ªï ph·∫ßn H·ª£p Nh·∫•t,UPX
2858,AAA,HSX,STOCK,An Ph√°t Bioplastics,C√¥ng ty C·ªï ph·∫ßn Nh·ª±a An Ph√°t Xanh,STO
2859,A32,UPCOM,STOCK,C√¥ng ty 32,C√¥ng ty C·ªï ph·∫ßn 32,UPX
2860,41I1F7000,HNX,FU,VN30 Index Futures 072025,VN30 Index Futures 072025,FIO

In [8]:
# # Xu·∫•t d·ªØ li·ªáu ra file csv
# listing.symbols_by_exchange().to_csv('assets/data/symbols_by_exchange.csv', index=False)

### Li·ªát k√™ m√£ CP theo ng√†nh icb

In [9]:
listing.symbols_by_industries()

,symbol,organ_name,icb_name3,icb_name2,icb_name4,com_type_code,icb_code1,icb_code2,icb_code3,icb_code4
0,ALT,C√¥ng ty C·ªï ph·∫ßn VƒÉn h√≥a T√¢n B√¨nh,Truy·ªÅn th√¥ng,Truy·ªÅn th√¥ng,"S√°ch, ·∫•n b·∫£n & s·∫£n ph·∫©m vƒÉn h√≥a",CT,5000,5500,5550,5557
1,APH,C√¥ng ty C·ªï ph·∫ßn T·∫≠p ƒëo√†n An Ph√°t Holdings,H√†ng c√¥ng nghi·ªáp,H√†ng & D·ªãch v·ª• C√¥ng nghi·ªáp,Containers & ƒê√≥ng g√≥i,CT,2000,2700,2720,2723
2,APC,C√¥ng ty C·ªï ph·∫ßn Chi·∫øu x·∫° An Ph√∫,D∆∞·ª£c ph·∫©m,Y t·∫ø,C√¥ng ngh·ªá sinh h·ªçc,CT,4000,4500,4570,4573
3,ASG,C√¥ng ty C·ªï ph·∫ßn T·∫≠p ƒëo√†n ASG,V·∫≠n t·∫£i,H√†ng & D·ªãch v·ª• C√¥ng nghi·ªáp,"Kho b√£i, h·∫≠u c·∫ßn v√† b·∫£o d∆∞·ª°ng",CT,2000,2700,2770,2777
4,CPA,C√¥ng ty C·ªï ph·∫ßn C√† ph√™ Ph∆∞·ªõc An,Bia v√† ƒë·ªì u·ªëng,Th·ª±c ph·∫©m v√† ƒë·ªì u·ªëng,ƒê·ªì u·ªëng & gi·∫£i kh√°t,CT,3000,3500,3530,3537
...,...,...,...,...,...,...,...,...,...,...
1587,VXP,C√¥ng ty C·ªï ph·∫ßn Thu·ªëc Th√∫ y Trung ∆∞∆°ng VETVACO,H√≥a ch·∫•t,H√≥a ch·∫•t,"S·∫£n ph·∫©m h√≥a d·∫ßu, N√¥ng d∆∞·ª£c & H√≥a ch·∫•t kh√°c",CT,1000,1300,1350,1357
1588,X26,C√¥ng ty C·ªï ph·∫ßn 26,H√†ng c√° nh√¢n,H√†ng c√° nh√¢n & Gia d·ª•ng,H√†ng May m·∫∑c,CT,3000,3700,3760,3763
1589,X77,C√¥ng ty C·ªï ph·∫ßn Th√†nh An 77,X√¢y d·ª±ng v√† V·∫≠t li·ªáu,X√¢y d·ª±ng v√† V·∫≠t li·ªáu,V·∫≠t li·ªáu x√¢y d·ª±ng & N·ªôi th·∫•t,CT,2000,2300,2350,2353
1590,CQT,C√¥ng ty C·ªï ph·∫ßn Xi mƒÉng Qu√°n Tri·ªÅu VVMI,X√¢y d·ª±ng v√† V·∫≠t li·ªáu,X√¢y d·ª±ng v√† V·∫≠t li·ªáu,V·∫≠t li·ªáu x√¢y d·ª±ng & N·ªôi th·∫•t,CT,2000,2300,2350,2353
1591,YTC,C√¥ng ty C·ªï ph·∫ßn Xu·∫•t nh·∫≠p kh·∫©u Y t·∫ø Th√†nh ph·ªë ...,Thi·∫øt b·ªã v√† D·ªãch v·ª• Y t·∫ø,Y t·∫ø,D·ª•ng c·ª• y t·∫ø,CT,4000,4500,4530,4537

In [11]:
# # Xu·∫•t d·ªØ li·ªáu ra file csv
# listing.symbols_by_industries().to_csv('assets/data/symbols_by_industries.csv', index=False)

### Danh s√°ch c·ªï phi·∫øu theo nh√≥m

In [12]:
# Li·ªát k√™ t·∫•t c·∫£ m√£ ch·ª©ng kho√°n theo nh√≥m ph√¢n lo·∫°i. V√≠ d·ª• HOSE, VN30, VNMidCap, VNSmallCap, VNAllShare, VN100, ETF, HNX, HNX30, HNXCon, HNXFin, HNXLCap, HNXMSCap, HNXMan, UPCOM, FU_INDEX (m√£ ch·ªâ s·ªë h·ª£p ƒë·ªìng t∆∞∆°ng lai), CW (ch·ª©ng quy·ªÅn)
listing.symbols_by_group('VN30')

0     ACB
1     BCM
2     BID
3     BVH
4     CTG
5     FPT
6     GAS
7     GVR
8     HDB
9     HPG
10    LPB
11    MBB
12    MSN
13    MWG
14    PLX
15    SAB
16    SHB
17    SSB
18    SSI
19    STB
20    TCB
21    TPB
22    VCB
23    VHM
24    VIB
25    VIC
26    VJC
27    VNM
28    VPB
29    VRE
Name: symbol, dtype: object

In [15]:
# # Xu·∫•t d·ªØ li·ªáu ra file csv
# listing.symbols_by_group('VN30').to_csv('assets/data/vn30_symbols.csv', index=False)

### Danh s√°ch m√£ ng√†nh theo m√£ icb

In [16]:
listing.industries_icb()

,icb_name,en_icb_name,icb_code,level
0,S·∫£n xu·∫•t D·∫ßu kh√≠,Oil & Gas Producers,0530,3
1,S·∫£n xu·∫•t v√† Khai th√°c d·∫ßu kh√≠,Exploration & Production,0533,4
2,Thi·∫øt b·ªã v√† D·ªãch v·ª• D·∫ßu kh√≠,Oil Equipment & Services,0573,4
3,"Nh·ª±a, cao su & s·ª£i",Commodity Chemicals,1353,4
4,"S·∫£n ph·∫©m h√≥a d·∫ßu, N√¥ng d∆∞·ª£c & H√≥a ch·∫•t kh√°c",Specialty Chemicals,1357,4
...,...,...,...,...
150,Ng√¢n h√†ng,Banks,8300,2
151,B·∫£o hi·ªÉm,Insurance,8500,2
152,B·∫•t ƒë·ªông s·∫£n,Real Estate,8600,2
153,D·ªãch v·ª• t√†i ch√≠nh,Financial Services,8700,2
154,C√¥ng ngh·ªá Th√¥ng tin,Technology,9500,2

In [17]:
# # Xu·∫•t d·ªØ li·ªáu ra file csv
# listing.industries_icb().to_csv('assets/data/industries_icb.csv', index=False)

## Quote: Gi√° ch·ª©ng kho√°n

> Kh√¥ng gi·ªëng nh∆∞ khi s·ª≠ d·ª•ng nh√≥m h√†m t·ªïng h·ª£p `Vnstock` nh∆∞ c·ªïng giao ti·∫øp v·ªõi ph·∫ßn m·ªÅm, b·∫°n c·∫ßn ƒë·ªãnh nghƒ©a th√¥ng tin `symbol` t·∫°i l·ªõp `Quote` khi n·∫°p ch∆∞∆°ng tr√¨nh v√† kh√¥ng th·ªÉ s·ª≠ d·ª•ng tham s·ªë `symbol` trong c√°c h√†m th√†nh ph·∫ßn. ƒê·ªÉ truy v·∫•n c√°c m√£ ch·ª©ng kho√°n kh√°c nhau, b·∫°n c·∫ßn khai b√°o t·∫°i `Quote`

In [18]:
# # L·∫•y th√¥ng tin chi ti·∫øt c·ªßa m·ªôt m√£ c·ªï phi·∫øu, ETF
quote = Quote(symbol='FPT')

In [19]:
# L·∫•y th√¥ng tin m√£ HƒêTL
quote = Quote(symbol='VN30F1M')
# ho·∫∑c
# quote = Quote(symbol='VN30F2506')

In [21]:
# L·∫•y th√¥ng tin m√£ ch·ªâ s·ªë
quote = Quote(symbol='VNINDEX')

In [22]:
# L·∫•y th√¥ng tin m√£ ch·ª©ng quy·ªÅn (CW)
quote = Quote(symbol='CFPT2314')

In [70]:
# Th√¥ng tin tr√°i phi·∫øu ni√™m y·∫øt
quote = Quote(symbol='CII424002')

#### Gi√° l·ªãch s·ª≠

In [73]:
quote = Quote(symbol='FPT')

In [74]:
df = quote.history(start='2024-01-01', end='2025-03-19', interval='1D')
df

          time    open    high     low   close    volume
0   2023-06-09   60.91   61.19   60.47   61.12    681805
1   2023-06-12   61.05   61.34   60.40   61.34    521246
2   2023-06-13   60.98   61.34   60.91   60.98    468477
3   2023-06-14   60.91   61.27   60.76   60.83    659704
4   2023-06-15   60.83   60.98   60.40   60.76    800193
..         ...     ...     ...     ...     ...       ...
439 2025-03-13  134.94  136.83  134.94  135.34   3630282
440 2025-03-14  134.45  135.14  129.69  130.28  16174178
441 2025-03-17  130.48  130.98  128.50  128.90   6750806
442 2025-03-18  128.99  131.08  128.90  128.90   5538119
443 2025-03-19  128.99  129.49  122.45  123.54  18229064

[444 rows x 6 columns]

In [75]:
# # T·∫•t c·∫£ dataframe d·ªØ li·ªáu s·∫Ω ƒë∆∞·ª£c g√°n thu·ªôc t√≠nh t√™n v√† lo·∫°i t√†i s·∫£n t∆∞∆°ng ·ª©ng
# print(f'M√£ ch·ª©ng kho√°n: {df.name}')
# print(f'Lo·∫°i t√†i s·∫£n: {df.category}')

#### Intraday: d·ªØ li·ªáu kh·ªõp l·ªánh

In [76]:
# D·ªØ li·ªáu kh·ªõp l·ªánh trong ng√†y giao d·ªãch realtime ho·∫∑c ng√†y g·∫ßn nh·∫•t (ngo√†i gi·ªù giao d·ªãch)
quote.intraday(page_size=10_000, show_log=False)

                          time  price  volume match_type         id
0    2025-06-13 09:17:21+07:00  115.4     100        Buy  309170202
1    2025-06-13 09:17:22+07:00  115.4     100        Buy  309170288
2    2025-06-13 09:17:22+07:00  115.4     500        Buy  309170327
3    2025-06-13 09:17:23+07:00  115.4     500        Buy  309170335
4    2025-06-13 09:17:25+07:00  115.4    1400        Buy  309170632
...                        ...    ...     ...        ...        ...
9995 2025-06-13 14:45:00+07:00  115.4   11200       Sell  309912498
9996 2025-06-13 14:45:00+07:00  115.4    2100       Sell  309912499
9997 2025-06-13 14:45:00+07:00  115.4     100       Sell  309912500
9998 2025-06-13 14:45:00+07:00  115.4     500       Sell  309912521
9999 2025-06-13 14:45:00+07:00  115.4     100       Sell  309912611

[10000 rows x 5 columns]

In [77]:
# B∆∞·ªõc gi√° v√† kh·ªëi l∆∞·ª£ng giao d·ªãch: realtime
quote.price_depth()

       price acc_volume acc_buy_volume acc_sell_volume acc_undefined_volume
0   116500.0    64300.0        23500.0         40800.0                  0.0
1   116400.0   112100.0        67800.0         44300.0                  0.0
2   116300.0   137500.0        65200.0         72300.0                  0.0
3   116200.0   208100.0        82900.0        125200.0                  0.0
4   116100.0   195200.0        39600.0        155600.0                  0.0
5   116000.0   287100.0        43400.0        243700.0                  0.0
6   115900.0   150900.0        97000.0         53900.0                  0.0
7   115800.0   241400.0        94200.0        147200.0                  0.0
8   115700.0   362800.0       208600.0        154200.0                  0.0
9   115600.0   521800.0       117300.0        404500.0                  0.0
10  115500.0   427100.0       133100.0        294000.0                  0.0
11  115400.0   865800.0       366700.0        499100.0                  0.0
12  115300.0   448200.0       116900.0        331300.0                  0.0
13  115200.0   546600.0       192900.0        353700.0                  0.0
14  115100.0   715600.0       221600.0        494000.0                  0.0
15  115000.0   774600.0       166800.0        607800.0                  0.0
16  114900.0   102600.0            0.0        102600.0                  0.0

## Trading: Giao d·ªãch

In [78]:
from vnstock.explorer.vci import Trading
trading = Trading()

### B·∫£ng gi√°

In [79]:
trading.price_board(['ACB', 'GB05F2506'])

     listing                                                                   \
      symbol ceiling   floor ref_price stock_type exchange     trading_status
0        ACB   22500   19600     21050      STOCK      HSX  TRADING_ACTIVATED
1  GB05F2506  111471  104979    108225         FU      HNX  TRADING_ACTIVATED

                                                   ...     bid_ask  \
  security_status last_trading_date  listed_share  ... ask_6_price
0               N              None  4.466658e+09  ...         NaN
1               N        13/06/2025           NaN  ...         0.0

                                                                              \
  ask_6_volume ask_7_price ask_7_volume ask_8_price ask_8_volume ask_9_price
0          NaN         NaN          NaN         NaN          NaN         NaN
1          0.0         0.0          0.0         0.0          0.0         0.0


  ask_9_volume ask_10_price ask_10_volume
0          NaN          NaN           NaN
1          0.0          0.0           0.0

[2 rows x 89 columns]

In [80]:
trading.price_board(['VCB','ACB','TCB','BID'], flatten_columns=True, drop_levels=[0]).T # B·ªè .T ƒë·ªÉ xoay tr·ªü l·∫°i ƒë√∫ng ki·ªÉu hi·ªÉn th·ªã b·∫£ng gi√°

                  0       1       2       3
symbol          VCB     ACB     TCB     BID
ceiling       59900   22500   33100   37750
floor         52100   19600   28800   32850
ref_price     56000   21050   30950   35300
_stock_type   STOCK   STOCK   STOCK   STOCK
...             ...     ...     ...     ...
ask_1_volume  40400   70600    2600   30600
ask_2_price   56400   21150   31250   35650
ask_2_volume  59600   83100  179500  167300
ask_3_price   56500   21200   31300   35700
ask_3_volume  93800  401900  471300  148900

[61 rows x 4 columns]

## Company: Th√¥ng tin c√¥ng ty

In [81]:
# # Kh·ªüi t·∫°o ƒë·ªëi t∆∞·ª£ng
# from vnstock import Vnstock
# company = Vnstock().stock(symbol='ACB', source='VCI').company

# ho·∫∑c
from vnstock.explorer.vci import Company
company = Company('ACB')

Lo·∫°i b·ªè ƒëo·∫°n m√£ `.head()` ƒë·ªÉ xem to√†n b·ªô d·ªØ li·ªáu thay v√¨ ch·ªâ l·∫•y 5 d√≤ng ƒë·∫ßu ti√™n.

#### H·ªì s∆°

In [82]:
company.overview()

,symbol,id,issue_share,history,company_profile,icb_name3,icb_name2,icb_name4,financial_ratio_issue_share,charter_capital
0,ACB,67505,4466657912,- Ng√†y 24/04/1993: Ng√¢n h√†ng Th∆∞∆°ng m·∫°i C·ªï ph...,Ng√¢n h√†ng Th∆∞∆°ng m·∫°i C·ªï ph·∫ßn √Å Ch√¢u (ACB) ƒë∆∞·ª£c...,Ng√¢n h√†ng,Ng√¢n h√†ng,Ng√¢n h√†ng,5136656599,44666579120000

#### C·ªï ƒë√¥ng

In [83]:
company.shareholders()

,id,share_holder,quantity,share_own_percent,update_date
0,82097397,Vietnam Enterprise Investments Limited,212880184,5.480880e-02,2024-09-13
1,82092255,Sather Gate Investments Limited,193907186,4.990000e-02,2024-05-15
2,82073703,Estes Investments Limited,83010435,4.990000e-02,2024-05-15
3,82090028,Ph·∫°m Th·ªã Thu H√†,285000,4.990000e-02,2016-05-20
4,82094227,Tr·∫ßn H√πng Huy,153062159,3.940000e-02,2025-01-24
...,...,...,...,...,...
82,82086414,Nguy·ªÖn Th·ªã Tuy·∫øt V√¢n,88722,1.730000e-05,2025-01-24
83,82091780,Qu·ªπ ƒê·∫ßu t∆∞ C·ªï phi·∫øu NƒÉng ƒë·ªông B·∫£o Vi·ªát,22065,1.327000e-05,2025-02-03
84,82071973,ƒêinh Th·ªã Hoa,67200,1.200000e-05,2025-01-24
85,82067883,C√¥ng ty C·ªï ph·∫ßn Ch·ª©ng kho√°n Thi√™n Vi·ªát,5285,1.500000e-06,2022-07-25
86,82081670,Nguy·ªÖn H·ªìng Nga,2008,7.000000e-07,2022-08-31

#### C√¥ng ty con

In [84]:
company.subsidiaries()

,id,sub_organ_code,ownership_percent,organ_name,type
0,23245572,ACBA,1,C√¥ng Ty TNHH Qu·∫£n L√Ω N·ª£ V√† Khai Th√°c T√†i S·∫£n N...,c√¥ng ty con
1,23245573,ACBL,1,C√¥ng Ty TNHH M·ªôt Th√†nh Vi√™n Cho Thu√™ T√†i Ch√≠nh...,c√¥ng ty con
2,23245574,ACBS,1,C√¥ng ty TNHH Ch·ª©ng kho√°n ACB,c√¥ng ty con
0,23245576,ACBD,None,C√îNG TY C·ªî PH·∫¶N D·ªäCH V·ª§ B·∫¢O V·ªÜ NG√ÇN H√ÄNG √Å CH√ÇU,c√¥ng ty li√™n k·∫øt
1,23245575,SGGS,None,C√¥ng ty C·ªï ph·∫ßn S√†i G√≤n Kim ho√†n ACB- SJC,c√¥ng ty li√™n k·∫øt

#### C√¥ng ty li√™n k·∫øt

In [85]:
# Ph∆∞∆°ng th·ª©c n√†y kh√¥ng c√≥ trong ngu·ªìn TCBS
company.affiliate()

,id,sub_organ_code,organ_name,ownership_percent
0,23245576,ACBD,C√îNG TY C·ªî PH·∫¶N D·ªäCH V·ª§ B·∫¢O V·ªÜ NG√ÇN H√ÄNG √Å CH√ÇU,None
1,23245575,SGGS,C√¥ng ty C·ªï ph·∫ßn S√†i G√≤n Kim ho√†n ACB- SJC,None

#### L√£nh ƒë·∫°o

In [86]:
company.officers(filter_by='working').head() # filter_by='all' ho·∫∑c 'working' ho·∫∑c 'resigned'

,id,officer_name,officer_position,position_short_name,update_date,officer_own_percent,quantity
0,6,Tr·∫ßn H√πng Huy,Ch·ªß t·ªãch H·ªôi ƒë·ªìng Qu·∫£n tr·ªã,Ch·ªß t·ªãch HƒêQT,2025-01-24,0.0394,153062159
1,7,ƒê·∫∑ng Thu Th·ªßy,Th√†nh vi√™n H·ªôi ƒë·ªìng Qu·∫£n tr·ªã,TV HƒêQT,2025-01-24,0.0137,53350036
2,11,ƒê·∫∑ng Ph√∫ Vinh,Gi√°m ƒë·ªëc kh·ªëi,Gƒê Kh·ªëi,2025-01-24,0.0042,16454507
3,13,ƒê·ªó Minh To√†n,T·ªïng Gi√°m ƒë·ªëc,TGƒê,2025-01-24,0.0008,3202886
4,8,Nguy·ªÖn Th√†nh Long,Ph√≥ Ch·ªß t·ªãch H·ªôi ƒë·ªìng Qu·∫£n tr·ªã,Ph√≥ Ch·ªß t·ªãch HƒêQT,2025-01-24,0.0004,1647067

#### Tin t·ª©c

In [87]:
company.news().head(3)

,id,news_title,news_sub_title,friendly_sub_title,news_image_url,news_source_link,created_at,public_date,updated_at,lang_code,news_id,news_short_content,news_full_content,close_price,ref_price,floor,ceiling,price_change_pct
0,7644135,ACB: B√°o c√°o k·∫øt qu·∫£ ph√°t h√†nh c·ªï phi·∫øu ƒë·ªÉ tr·∫£...,,,https://cdn.fiingroup.vn/medialib/127889/I/202...,https://www.hsx.vn/vi/tin-tuc/acb-bao-cao-ket-...,None,1748863637000,None,vi,11591997,,<p>Ng√¢n h√†ng Th∆∞∆°ng m·∫°i C·ªï ph·∫ßn √Å Ch√¢u c√¥ng b·ªë...,21100.0,21100.0,19650.0,22550.0,0.000000
1,7644120,ACB: Ngh·ªã quy·∫øt HƒêQT v·ªÅ ph∆∞∆°ng √°n ph√°t h√†nh tr...,,,https://cdn.fiingroup.vn/medialib/127889/I/202...,https://www.hsx.vn/vi/tin-tuc/acb-nghi-quyet-h...,None,1748861109000,None,vi,11591974,,<p>Ng√¢n h√†ng Th∆∞∆°ng m·∫°i C·ªï ph·∫ßn √Å Ch√¢u c√¥ng b·ªë...,21100.0,21100.0,19650.0,22550.0,0.000000
2,7624359,ACB: Th√¥ng b√°o thay ƒë·ªïi s·ªë l∆∞·ª£ng c·ªï phi·∫øu c√≥ q...,,,https://cdn.fiingroup.vn/medialib/127889/I/202...,https://www.hsx.vn/vi/tin-tuc/acb-thong-bao-th...,None,1748540593000,None,vi,11591078,,<p>Ng√¢n h√†ng Th∆∞∆°ng m·∫°i C·ªï ph·∫ßn √Å Ch√¢u th√¥ng b...,21300.0,21400.0,19950.0,22850.0,-0.004673

#### S·ª± ki·ªán

In [88]:
company.events().head(3)

,id,event_title,en__event_title,public_date,issue_date,source_url,event_list_code,ratio,value,record_date,exright_date,event_list_name,en__event_list_name
0,18129,Ph√°t h√†nh c·ªï phi·∫øu,,2010-11-18,2010-11-30,,ISS,NaN,NaN,2010-11-30,2010-11-26,Ph√°t h√†nh c·ªï phi·∫øu,Share Issue
1,18140,ACB-Ph√°t h√†nh c·ªï phi·∫øu tr·∫£ c·ªï t·ª©c cho CƒêHH t·ª∑ ...,ACB-Issues dividend shares for existing shareh...,2016-11-21,2016-12-01,http://fiinpro.com/News/Detail/313345?lang=vi-VN,ISS,NaN,NaN,2016-12-02,2016-12-01,Ph√°t h√†nh c·ªï phi·∫øu,Share Issue
2,18144,ACB-Ph√°t h√†nh c·ªï phi·∫øu tr·∫£ c·ªï t·ª©c t·ª∑ l·ªá 15%,ACB-Issues dividend shares at 15%,2018-08-29,2018-09-06,http://fiinpro.com/News/Detail/2278207?lang=vi-VN,ISS,0.15,0.0,2018-09-07,2018-09-06,Ph√°t h√†nh c·ªï phi·∫øu,Share Issue

#### B√°o c√°o ph√¢n t√≠ch

In [89]:
company.reports()

,date,description,link,name
0,2025-05-27T00:00:00Z,"- Ch√∫ng t√¥i ƒëi·ªÅu ch·ªânh gi·∫£m 2,4% gi√° m·ª•c ti√™u ...",https://www.vietcap.com.vn/trung-tam-phan-tich...,"ACB [MUA +32,3%] - NIM d·ª± ki·∫øn s·∫Ω ph·∫£i ch·ªãu √°p..."
1,2025-04-24T00:00:00Z,1. T√°c ƒë·ªông c·ªßa Thu·∫ø quan ƒë·ªëi v·ªõi ACB: T√°c ƒë·ªôn...,https://www.vietcap.com.vn/trung-tam-phan-tich...,ACB - K·ª≥ v·ªçng t√≠n d·ª•ng tƒÉng m·∫°nh v√† NIM c·∫£i th...
2,2025-04-23T00:00:00Z,Ng√¢n h√†ng TMCP √Å Ch√¢u (ACB) c√¥ng b·ªë KQKD qu√Ω 1...,https://www.vietcap.com.vn/trung-tam-phan-tich...,ACB - L·ª£i nhu·∫≠n th·∫•p h∆°n k·ª≥ v·ªçng do NIM gi·∫£m -...
3,2025-04-08T00:00:00Z,Ch√∫ng t√¥i ƒë√£ tham d·ª± ƒêHCƒê c·ªßa Ng√¢n h√†ng TMCP √Å...,https://www.vietcap.com.vn/trung-tam-phan-tich...,ACB - TƒÉng tr∆∞·ªüng t√≠n d·ª•ng ƒë∆∞·ª£c k·ª≥ v·ªçng s·∫Ω n·∫±m...
4,2025-01-22T00:00:00Z,Ng√¢n h√†ng Th∆∞∆°ng M·∫°i C·ªï Ph·∫ßn √Å Ch√¢u (ACB) ƒë√£ c...,https://www.vietcap.com.vn/trung-tam-phan-tich...,ACB - T·∫≠p trung v√†o tƒÉng tr∆∞·ªüng t√≠n d·ª•ng h∆°n t...
5,2024-10-24T00:00:00Z,Ng√¢n h√†ng TMCP √Å Ch√¢u (ACB) c√¥ng b·ªë KQKD 9 th√°...,https://www.vietcap.com.vn/trung-tam-phan-tich...,"ACB ‚Äì NOII th·∫•p h∆°n d·ª± ki·∫øn, ·∫£nh h∆∞·ªüng ti√™u c·ª±..."
6,2024-09-09T00:00:00Z,- Ch√∫ng t√¥i ti·∫øp t·ª•c duy tr√¨ gi√° m·ª•c ti√™u ƒë·ªëi ...,https://www.vietcap.com.vn/trung-tam-phan-tich...,"ACB [MUA +35,0%] - TƒÉng d·ª± b√°o tƒÉng tr∆∞·ªüng t√≠n..."
7,2024-07-23T00:00:00Z,ACB ƒë√£ c√¥ng b·ªë KQKD n·ª≠a ƒë·∫ßu nƒÉm 2024 v·ªõi thu n...,https://www.vietcap.com.vn/trung-tam-phan-tich...,"ACB - T√≠n d·ª•ng tƒÉng tr∆∞·ªüng m·∫°nh, ch·∫•t l∆∞·ª£ng t√†..."
8,2024-06-04T00:00:00Z,"- Ch√∫ng t√¥i ƒëi·ªÅu ch·ªânh tƒÉng 8,6% gi√° m·ª•c ti√™u ...",https://www.vietcap.com.vn/trung-tam-phan-tich...,"ACB [MUA +33,7%] - NIM t∆∞∆°ng ƒë·ªëi ƒëi ngang tron..."
9,2024-04-26T00:00:00Z,"ACB ƒë√£ c√¥ng b·ªë KQKD qu√Ω 1/2024 v·ªõi TOI ƒë·∫°t 8,2...",https://www.vietcap.com.vn/trung-tam-phan-tich...,"ACB ‚Äì NOII th·∫•p, ch·∫•t l∆∞·ª£ng t√†i s·∫£n ƒë∆∞·ª£c duy t..."

#### T√¨nh h√¨nh t√†i ch√≠nh

In [90]:
company.ratio_summary()

,symbol,year_report,length_report,update_date,revenue,revenue_growth,net_profit,net_profit_growth,ebit_margin,roe,...,rtq4,charter_capital_ratio,rtq10,dividend,ebitda,ebit,le,de,ccc,rtq17
0,ACB,2025,1,1745422597663,13327306000000,0.111758,3678266000000,-0.058164,0,0.204361,...,0,1.949435,9.240355,0.047506,0,0,0,9.240355,None,0

#### Th·ªëng k√™ giao d·ªãch

In [91]:
company.trading_stats()

,symbol,exchange,ev,ceiling,floor,ref_price,open,match_price,close_price,price_change,...,high_price_1y,low_price_1y,pct_low_change_1y,pct_high_change_1y,foreign_volume,foreign_room,avg_match_volume_2w,foreign_holding_room,current_holding_ratio,max_holding_ratio
0,ACB,HOSE,108126621408950,22500,19600,21050,21000,21050,21050,0,...,22391,17337,0.155711,-0.054616,1835701,1339997373,6498248,1336678637,0.299257,0.3

## Finance: B√°o c√°o t√†i ch√≠nh

In [92]:
from vnstock.explorer.vci import Finance
fin =  Finance(symbol='VCI')

### B·∫£ng c√¢n ƒë·ªëi k·∫ø to√°n

In [93]:
fin.balance_sheet(period='year', lang='vi', dropna=True)

,CP,NƒÉm,T√ÄI S·∫¢N NG·∫ÆN H·∫†N (ƒë·ªìng),Ti·ªÅn v√† t∆∞∆°ng ƒë∆∞∆°ng ti·ªÅn (ƒë·ªìng),Gi√° tr·ªã thu·∫ßn ƒë·∫ßu t∆∞ ng·∫Øn h·∫°n (ƒë·ªìng),C√°c kho·∫£n ph·∫£i thu ng·∫Øn h·∫°n (ƒë·ªìng),H√†ng t·ªìn kho r√≤ng,T√†i s·∫£n l∆∞u ƒë·ªông kh√°c,T√ÄI S·∫¢N D√ÄI H·∫†N (ƒë·ªìng),T√†i s·∫£n c·ªë ƒë·ªãnh (ƒë·ªìng),...,"H√†ng t·ªìn kho, r√≤ng (ƒë·ªìng)",T√†i s·∫£n l∆∞u ƒë·ªông kh√°c (ƒë·ªìng),C·ªï phi·∫øu ph·ªï th√¥ng (ƒë·ªìng),V·ªën g√≥p c·ªßa ch·ªß s·ªü h·ªØu (ƒë·ªìng),Vay v√† n·ª£ thu√™ t√†i ch√≠nh d√†i h·∫°n (ƒë·ªìng),Ng∆∞·ªùi mua tr·∫£ ti·ªÅn tr∆∞·ªõc ng·∫Øn h·∫°n (ƒë·ªìng),Vay v√† n·ª£ thu√™ t√†i ch√≠nh ng·∫Øn h·∫°n (ƒë·ªìng),Tr·∫£ tr∆∞·ªõc d√†i h·∫°n (ƒë·ªìng),T√†i s·∫£n d√†i h·∫°n kh√°c (ƒë·ªìng),L·ª¢I √çCH C·ª¶A C·ªî ƒê√îNG THI·ªÇU S·ªê
0,VCI,2024,26491835561026,4743771932745,21072524575199,506858248065,0,168680805017,100288918214,37268698440,...,0,135374861200,7.180995e+12,7180994800000,0,2743133560,12573864000000,6238956911,0,0.000000e+00
1,VCI,2023,17174448616966,787897819240,15097165308797,1094491429414,0,194894059515,80686039559,23425609453,...,0,147257185100,4.375000e+12,4375000000000,0,378319774,8979275000000,7943878800,0,0.000000e+00
2,VCI,2022,14157693071824,3423501614803,10562264962864,120085485886,0,51841008271,85058244998,23496558588,...,0,46136989800,4.354999e+12,4354999010000,0,221000000,6326207142857,13290531600,0,0.000000e+00
3,VCI,2021,16568965942558,1131748599533,14998113044339,285206345277,0,153897953409,67299004559,13155825424,...,0,150714917648,3.330000e+12,3330000000000,0,52551076244,6362680000000,10702485700,0,0.000000e+00
4,VCI,2020,8312170798945,642512983590,6697916243107,221798617565,0,97527648804,70234326495,14384201512,...,0,91333803000,1.656000e+12,1656000000000,0,7971369863,2696130000000,12950546970,0,0.000000e+00
5,VCI,2019,7173102515011,794511762602,5817229478552,747087592357,0,165433739031,69857713462,9907318916,...,0,164204396000,1.644000e+12,1644000000000,0,210000000,1450980000000,17085900679,0,0.000000e+00
6,VCI,2018,6430493843962,1144361568890,5252959790479,30487868695,0,2684615898,79502079245,18226354386,...,0,0,1.629999e+12,1629998900000,0,126324890101,984860000000,25494063880,0,0.000000e+00
7,VCI,2017,6342806740944,486703202803,5709256554482,28256236703,0,118590746956,59205004260,25326131092,...,0,116156411000,1.200000e+12,1200000000000,0,462392057000,1434460418662,2171535344,0,0.000000e+00
8,VCI,2016,3075625891871,545670784533,2481417250820,44869461531,0,7607339062,34921874969,9489824544,...,0,1335936000,1.032000e+12,1032000000000,0,571264678998,627508000000,4433448206,0,7.721605e+10
9,VCI,2015,2423478575254,158181741192,2092718191471,78849205458,0,92517941380,39867670505,14899441202,...,0,87885991500,5.000000e+11,500000000000,0,799974087998,535500000000,9817929938,0,7.475699e+10
10,VCI,2014,2707101348631,618777857754,1939716412996,141064801745,14179400,7528096736,63219168401,18390029859,...,14179400,3095401526,5.000000e+11,500000000000,0,840646942003,266511750000,14560154043,14160000000,7.604128e+10
11,VCI,2013,2090711345801,312645301464,1659030664666,117641213076,16677400,1377489195,41576018914,11027268785,...,16677400,87777500,0.000000e+00,398400000000,0,470366997300,648400000000,16231644217,0,0.000000e+00
12,VCI,2011,1795452129469,111616718751,1059922610501,614818783909,12320284,9081696024,622201775573,7612776214,...,12320284,6609715987,3.780000e+11,378000000000,500000000000,121749992655,582426780000,0,594640525000,0.000000e+00

In [94]:
fin.balance_sheet(period='quarter', lang='en', dropna=True).head()

,ticker,yearReport,lengthReport,CURRENT ASSETS (Bn. VND),Cash and cash equivalents (Bn. VND),Short-term investments (Bn. VND),Accounts receivable (Bn. VND),Net Inventories,Other current assets,LONG-TERM ASSETS (Bn. VND),...,Other current assets (Bn. VND),Common shares (Bn. VND),Paid-in capital (Bn. VND),Long-term borrowings (Bn. VND),Advances from customers (Bn. VND),Short-term borrowings (Bn. VND),Long-term prepayments (Bn. VND),Other long-term assets (Bn. VND),Goodwill,MINORITY INTERESTS
0,VCI,2025,1,23620977742780,2302263974886,19710214115776,1256719415203,0,351780236915,106647519669,...,325110955850,7.180995e+12,7180994800000,0,19034969033,10310840000000,4964163668,0,0,0.0
1,VCI,2024,4,26491835561026,4743771932745,21072524575199,506858248065,0,168680805017,100288918214,...,135374861200,7.180995e+12,7180994800000,0,2743133560,12573864000000,6238956911,0,0,0.0
2,VCI,2024,3,20322217963459,2543516547760,17408880681428,235746508338,0,134074225933,92945134178,...,122374861200,5.744695e+12,5744694800000,0,4431803623,10832654000000,7503462322,0,0,0.0
3,VCI,2024,2,23009916452730,3903157759657,17775135464006,931122579216,0,400500649851,95455335905,...,372374861200,4.419000e+12,4419000000000,0,1753351687,12392104000000,8879984392,0,0,0.0
4,VCI,2024,1,19458498860847,1040594399692,17454154906730,702530886335,0,261218668090,86105265555,...,227872273100,4.375000e+12,4375000000000,0,1083817322,10239557000000,9017164629,0,0,0.0

### B√°o c√°o l√£i l·ªó

In [95]:
fin.income_statement(period='year', lang='vi', dropna=True).head()

,CP,NƒÉm,Doanh thu (ƒë·ªìng),TƒÉng tr∆∞·ªüng doanh thu (%),L·ª£i nhu·∫≠n sau thu·∫ø c·ªßa C·ªï ƒë√¥ng c√¥ng ty m·∫π (ƒë·ªìng),TƒÉng tr∆∞·ªüng l·ª£i nhu·∫≠n (%),Doanh thu thu·∫ßn,Gi√° v·ªën h√†ng b√°n,L√£i g·ªôp,Thu nh·∫≠p t√†i ch√≠nh,...,L·ª£i nhu·∫≠n kh√°c,LN tr∆∞·ªõc thu·∫ø,Chi ph√≠ thu·∫ø TNDN hi·ªán h√†nh,Chi ph√≠ thu·∫ø TNDN ho√£n l·∫°i,L·ª£i nhu·∫≠n thu·∫ßn,C·ªï ƒë√¥ng thi·ªÉu s·ªë,C·ªï ƒë√¥ng c·ªßa C√¥ng ty m·∫π,Doanh thu b√°n h√†ng v√† cung c·∫•p d·ªãch v·ª•,Thu nh·∫≠p kh√°c,Thu nh·∫≠p/Chi ph√≠ kh√°c
0,VCI,2024,3695525335470,0.494675,910692113293,0.851359,3695525335470,-1717402022529,1978123312941,5.063321e+10,...,2785303975,1089337104906,-178605980097,-39011516,910692113293,0,910692113293,3695525335470,3094145678,-308841703
1,VCI,2023,2472460543397,-0.216644,491904659394,-0.433927,2472460543397,-1063597101525,1408863441872,2.369615e+10,...,128411319,570138640134,-64320454739,-13913526001,491904659394,0,491904659394,2472460543397,132390105,-3978786
2,VCI,2022,3156242736345,-0.148588,868978185802,-0.420186,3156242736345,-1398531179478,1757711556867,3.554843e+10,...,43696276107,1059738713385,-250981079495,60220551912,868978185802,0,868978185802,3156242736345,44543029091,-846752984
3,VCI,2021,3707068724492,1.143320,1498718375328,0.949141,3707068724492,-1326133822522,2380934901970,2.561687e+10,...,-267786912,1850585393088,-309748513618,-42118504142,1498718375328,0,1498718375328,3707068724492,69316632,-337103544
4,VCI,2020,1729591590563,0.122423,768912289421,0.109253,1729591590563,-522004485232,1207587105331,5.858556e+09,...,621078878,951038957081,-182422798514,296130854,768912289421,0,768912289421,1729591590563,621078878,0

In [96]:
fin.income_statement(period='quarter', lang='en', dropna=True).head()

,ticker,yearReport,lengthReport,Revenue (Bn. VND),Revenue YoY (%),Attribute to parent company (Bn. VND),Attribute to parent company YoY (%),Net Sales,Cost of Sales,Gross Profit,...,Net other income/expenses,Profit before tax,Business income tax - current,Business income tax - deferred,Net Profit For the Year,Minority Interest,Attributable to parent company,Sales,Other income,Other Income/Expenses
0,VCI,2025,1,850928963332,0.055328,294867782406,0.491065,850928963332,-313821357598,537107605734,...,15042153051,355107020678,-72883103138,12643864866,294867782406,0,294867782406,850928963332,15107153051,-65000000
1,VCI,2024,4,998995850627,0.239917,218376745828,0.776135,998995850627,-519893652425,479102198202,...,21194452,253335115979,-35884665831,926295680,218376745828,0,218376745828,998995850627,23636364,-2441912
2,VCI,2024,3,974360554621,0.461496,215352225175,0.203064,974360554621,-468140246243,506220308378,...,0,264695399242,-40189361297,-9153812770,215352225175,0,215352225175,974360554621,0,0
3,VCI,2024,2,915851554761,0.828529,279206679897,1.388492,915851554761,-359336052126,556515502635,...,2826585413,343766121537,-64821621464,262179824,279206679897,0,279206679897,915851554761,2837985204,-11399791
4,VCI,2024,1,806317375461,0.615187,197756462393,1.706977,806317375461,-370032071735,436285303726,...,-62475890,227540468148,-37710331505,7926325750,197756462393,0,197756462393,806317375461,232524110,-295000000

### B√°o c√°o l∆∞u chuy·ªÉn ti·ªÅn t·ªá

In [97]:
fin.cash_flow(period='year', dropna=True).head()

,ticker,yearReport,Net Profit/Loss before tax,Depreciation and Amortisation,Provision for credit losses,Unrealized foreign exchange gain/loss,Profit/Loss from investing activities,Interest Expense,Interest income and dividends,Operating profit before changes in working capital,...,Payments for share repurchases,Proceeds from borrowings,Repayment of borrowings,Dividends paid,Cash flows from financial activities,Net increase/decrease in cash and cash equivalents,Cash and cash equivalents,Cash and Cash Equivalents at the end of period,_Increase/Decrease in receivables,_Increase/Decrease in payables
0,VCI,2024,1089337104906,10751194638,4516800000,0,0,764124674808,-8.608679e+10,-5169139240487,...,0,28212221000000,-24737632000000,-177803580300,7371225419700,3955874113505,787897819240,4743771932745,0,65609975849
1,VCI,2023,570138640134,9679599271,11292000000,0,0,562553033255,-1.032191e+11,-5407321967895,...,0,20322010000000,-18096042142857,-522119971000,1727849074143,-2635603795563,3423501614803,787897819240,0,3923102445
2,VCI,2022,1059738713385,9647191174,0,0,154602984,477360036322,-5.948490e+10,2006811362129,...,0,15126047142857,-16579490000000,0,-1428442857143,2291753015270,1131748599533,3423501614803,0,-119194100124
3,VCI,2021,1850585393088,7496942452,-214202387,0,0,330776772616,-4.785212e+10,-5732733292320,...,0,16591566600000,-11629266600000,-730123222800,4245676777200,489235615943,642512983590,1131748599533,5939376000,88803338332
4,VCI,2020,951038957081,10634646105,-35400000,0,-500000000,173513458172,-2.094800e+10,-1673271187005,...,-852000000,7065840000000,-6233940000000,-411641446500,432858721500,-151998779012,794511762602,642512983590,57321090000,-265045502541

In [98]:
fin.income_statement(period='quarter', lang='en', dropna=True).head()

,ticker,yearReport,lengthReport,Revenue (Bn. VND),Revenue YoY (%),Attribute to parent company (Bn. VND),Attribute to parent company YoY (%),Net Sales,Cost of Sales,Gross Profit,...,Net other income/expenses,Profit before tax,Business income tax - current,Business income tax - deferred,Net Profit For the Year,Minority Interest,Attributable to parent company,Sales,Other income,Other Income/Expenses
0,VCI,2025,1,850928963332,0.055328,294867782406,0.491065,850928963332,-313821357598,537107605734,...,15042153051,355107020678,-72883103138,12643864866,294867782406,0,294867782406,850928963332,15107153051,-65000000
1,VCI,2024,4,998995850627,0.239917,218376745828,0.776135,998995850627,-519893652425,479102198202,...,21194452,253335115979,-35884665831,926295680,218376745828,0,218376745828,998995850627,23636364,-2441912
2,VCI,2024,3,974360554621,0.461496,215352225175,0.203064,974360554621,-468140246243,506220308378,...,0,264695399242,-40189361297,-9153812770,215352225175,0,215352225175,974360554621,0,0
3,VCI,2024,2,915851554761,0.828529,279206679897,1.388492,915851554761,-359336052126,556515502635,...,2826585413,343766121537,-64821621464,262179824,279206679897,0,279206679897,915851554761,2837985204,-11399791
4,VCI,2024,1,806317375461,0.615187,197756462393,1.706977,806317375461,-370032071735,436285303726,...,-62475890,227540468148,-37710331505,7926325750,197756462393,0,197756462393,806317375461,232524110,-295000000

### Ch·ªâ s·ªë t√†i ch√≠nh

In [99]:
fin.ratio(period='year', lang='vi', flatten_columns=True, drop_levels=[0], dropna=True).head()

,CP,NƒÉm,K·ª≥,(Vay NH+DH)/VCSH,N·ª£/VCSH,TSCƒê / V·ªën CSH,V·ªën CSH/V·ªën ƒëi·ªÅu l·ªá,V√≤ng quay t√†i s·∫£n,V√≤ng quay TSCƒê,S·ªë ng√†y thu ti·ªÅn b√¨nh qu√¢n,...,ƒê√≤n b·∫©y t√†i ch√≠nh,P/B,V·ªën h√≥a (ƒë·ªìng),S·ªë CP l∆∞u h√†nh (Tri·ªáu CP),P/E,P/S,P/Cash Flow,EPS (VND),BVPS (VND),EV/EBITDA
0,VCI,2024,5,0.971382,1.054349,0.002879,1.802578,0.168564,121.775022,0.0,...,2.054349,1.961080,25384816618000,718099480,27.874203,6.869068,-7.501315,1268.197706,18025.783068,18.010726
1,VCI,2023,5,1.218152,1.340876,0.003178,1.026491,0.156992,105.385605,0.0,...,2.340876,1.970499,14525000000000,437500000,29.528080,5.874715,-3.334822,1124.353507,16848.524590,17.525975
2,VCI,2022,5,0.973942,1.192721,0.003617,0.904536,0.204426,172.225781,0.0,...,2.192721,2.866248,18617620767750,435499901,21.424727,5.898666,4.975461,1995.357941,14914.970490,12.729467
3,VCI,2021,5,0.972610,1.543047,0.002011,0.910997,0.296344,269.213152,0.0,...,2.543047,1.183493,7742250000000,333000000,5.165914,2.088510,-2.064593,4500.655782,19645.234971,5.895364
4,VCI,2020,5,0.596293,0.853905,0.003181,0.629646,0.221383,142.402909,0.0,...,1.853905,2.666309,12055680000000,165600000,15.678875,6.970247,-21.093469,4643.190154,27303.662559,12.313747

In [100]:
fin.ratio(period='quarter', lang='en', flatten_columns=True, drop_levels=[0], dropna=True).head()

,ticker,yearReport,lengthReport,(ST+LT borrowings)/Equity,Debt/Equity,Fixed Asset-To-Equity,Owners' Equity/Charter Capital,Asset Turnover,Fixed Asset Turnover,Days Sales Outstanding,...,Financial Leverage,P/B,Market Capital (Bn. VND),Outstanding Share (Mil. Shares),P/E,P/S,P/Cash Flow,EPS (VND),BVPS (VND),EV/EBITDA
0,VCI,2025,1,0.819614,0.886120,0.003394,1.751863,0.159426,105.942759,0.0,...,1.886120,2.017851,25384816618000,718099480,22.048814,6.787136,-9.369948,410.622470,17518.634866,17.094598
1,VCI,2024,4,0.971382,1.054349,0.002879,1.802578,0.168564,121.775022,0.0,...,2.054349,2.024877,26210631020000,718099480,23.730837,7.092532,-6.386280,304.103752,18025.783068,18.707439
2,VCI,2024,3,1.253482,1.362305,0.003381,1.203462,0.174413,131.475148,0.0,...,2.362305,1.806066,22871468438000,718099480,23.303298,6.530553,-17.723150,299.891911,17635.011093,17.958349
3,VCI,2024,2,1.398891,1.608265,0.003615,1.233606,0.166335,129.528632,0.0,...,2.608265,2.379972,21083029916000,574469480,26.866048,6.599683,-4.975656,486.025263,15420.349585,17.950658
4,VCI,2024,1,1.252192,1.390102,0.002676,1.138743,0.162937,130.111085,0.0,...,2.390102,2.571899,21167010000000,441900000,33.973894,7.615216,-4.399652,447.514058,18624.368974,20.739556