<a target="_blank" href="https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/2_international_market.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Mục lục

1. Chứng khoán Việt Nam [tại đây](https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/1_vietnam_stock_vnstock3.ipynb)
2. Chứng khoán quốc tế: Forex, Crypto, Chỉ số [tại đây](https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/2_international_market.ipynb)
3. Dữ liệu Thị trường, hàng hoá [tại đây](https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/3_commodities_vnstock3.ipynb)
4. Biểu diễn dữ liệu trực quan từ Vnstock3 [tại đây](https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/5_visualization_data_exploration_vnstock3.ipynb)

# I. Cài đặt

## Cài đặt thư viện

In [ ]:
!pip install -U vnstock

## Nạp thư viện lần đầu

> Bạn có thể nạp toàn bộ các module của thư viện vào môi trường làm việc nếu chưa biết rõ mình cần gì hoặc chọn từng module riêng biệt để nạp vào khi đã quen thuộc.

In [1]:
## Nạp toàn bộ thư viện
# from vnstock import *

## Nạp Wrapper làm việc chính (UI chính của thư viện)
from vnstock import Vnstock

# II. Tìm kiếm mã niêm yết được hỗ trợ bởi MSN

In [2]:
from vnstock.explorer.msn.listing import Listing
Listing(api_version='20240530').search_symbol_id('USDEUR')

,symbol,symbol_id,exchange_name,exchange_code_mic,short_name,friendly_name,eng_name,description,local_name,locale
0,USDEUR,avyn9c,FOREX,FOREX,US Dollar/Euro FX Cross Rate,US Dollar/Euro FX Cross Rate,US Dollar/Euro FX Cross Rate,,US Dollar/Euro FX Cross Rate,en-us
1,,arjffr,,LU,FS - HG Bd USD (EURh) Fa,FS - HG Bd USD (EURh) Fa,Focused SICAV - High Grade Bond USD (EURh) F-a,,Focused SICAV - High Grade Bond USD (EURh) F-a,lb-lu
2,,aslrm7,,LU,UBS(L)ES-LT Thms USDEURh Pa,UBS(L)ES-LT Thms USDEURh Pa,UBS (Lux) Eq SICAV-Long Term Themes (USD)(EURh...,,UBS (Lux) Eq SICAV-Long Term Themes (USD)(EURh...,lb-lu
3,,arcg4c,,LU,FS - US CB Sus USD(EURh) Fa,FS - US CB Sus USD(EURh) Fa,Focused SICAV - US Corp Bd Sustain USD(EURh) F-a,,Focused SICAV - US Corp Bd Sustain USD(EURh) F-a,lb-lu
4,,at4aww,,LU,UBS(L)ES-LT Thms(USD)EURph Fa,UBS(L)ES-LT Thms(USD)EURph Fa,UBS (Lux) Eq SICAV-Lng Trm Thms (USD)(EURportf...,,UBS (Lux) Eq SICAV-Lng Trm Thms (USD)(EURportf...,lb-lu
5,,aswj4c,,LU,UBS L BS-GD (USD)(EURh) Pa,UBS L BS-GD (USD)(EURh) Pa,UBS (Lux) Bond S - Global Dynamic (USD)(EURh) P-a,,UBS (Lux) Bond S - Global Dynamic (USD)(EURh) P-a,lb-lu
6,,az2mzr,,LU,Focused SIC-WB Bd USD(EURh)F-a,Focused SIC-WB Bd USD(EURh)F-a,Focused SICAV-World Bank Bond USD (EUR hdg) F-acc,,Focused SICAV-World Bank Bond USD (EUR hdg) F-acc,lb-lu
7,,aslrjc,,LU,UBS(L)ES-LT Thms USDEURh Qa,UBS(L)ES-LT Thms USDEURh Qa,UBS (Lux) Eq SICAV-Long Term Themes (USD)(EURh...,,UBS (Lux) Eq SICAV-Long Term Themes (USD)(EURh...,lb-lu
8,,cen9rw,,LU,UBS L KS-Gl All USD (EURh) Pa,UBS L KS-Gl All USD (EURh) Pa,UBS (Lux) KSS-Global Allocation (USD) (EUR hgd...,,UBS (Lux) KSS-Global Allocation (USD) (EUR hgd...,lb-lu
9,,at5dsm,,LU,UBS L BS - GC (USD)(EURh) IXa,UBS L BS - GC (USD)(EURh) IXa,UBS (Lux) Bond S - Glob Corp (USD)(EURh) I-X-a,,UBS (Lux) Bond S - Glob Corp (USD)(EURh) I-X-a,lb-lu

# III. Truy xuất giá lịch sử: FX, Crypto, Index

## 3.1. Truy xuất theo mã symbol

### Forex

In [3]:
from vnstock import Vnstock
fx = Vnstock().fx(symbol='JPYVND', source='MSN')
df = fx.quote.history(start='2024-02-28', end='2024-05-25', interval='1D')
df

         time    open    high     low   close
0  2024-02-28  163.60  163.88  163.20  163.37
1  2024-02-29  163.37  165.13  163.36  164.28
2  2024-03-01  164.28  164.30  163.45  164.12
3  2024-03-04  164.15  164.43  163.76  163.92
4  2024-03-05  163.92  164.92  163.76  164.55
..        ...     ...     ...     ...     ...
58 2024-05-20  163.54  163.68  162.80  162.87
59 2024-05-21  162.87  163.37  162.47  163.02
60 2024-05-22  163.00  163.09  162.34  162.40
61 2024-05-23  162.40  162.70  162.01  162.28
62 2024-05-24  162.27  162.37  162.03  162.18

[63 rows x 5 columns]

### Crypto

In [4]:
crypto = Vnstock().crypto(symbol='BTC', source='MSN')
df = crypto.quote.history(start='2023-01-01', end='2024-12-31', interval='1D')
df

,time,open,high,low,close,volume
151,2023-01-07,4.289933e+08,4.329560e+08,4.259344e+08,4.319362e+08,367260131016105
152,2023-02-06,5.945057e+08,5.968291e+08,5.820081e+08,5.849104e+08,498497411180750
153,2023-03-08,5.714737e+08,5.739986e+08,5.608470e+08,5.661597e+08,580063722157155
154,2023-04-07,7.179048e+08,7.179852e+08,7.067836e+08,7.145647e+08,352587383009534
155,2023-05-07,7.526501e+08,7.598168e+08,7.253893e+08,7.364898e+08,405485323884695
156,2023-06-06,6.910968e+08,6.912720e+08,6.483429e+08,6.563673e+08,548158696632310
157,2023-07-06,7.842419e+08,7.867544e+08,7.701486e+08,7.775010e+08,318031735682934
158,2023-08-05,7.433632e+08,7.466170e+08,7.359983e+08,7.408079e+08,306693586884557
159,2023-09-04,6.591542e+08,6.647006e+08,6.578180e+08,6.617046e+08,228365124845785
160,2023-10-04,7.009103e+08,7.049601e+08,6.934637e+08,6.989159e+08,290671105474313
161,2023-11-03,9.030514e+08,9.152376e+08,8.765521e+08,8.902264e+08,535033079706980
162,2023-12-03,9.858028e+08,1.011019e+09,9.848681e+08,1.005857e+09,395807227392231
163,2024-01-02,1.077300e+09,1.125590e+09,1.075638e+09,1.125384e+09,469519410734010
164,2024-02-01,1.094270e+09,1.113919e+09,1.077777e+09,1.085005e+09,628684061649716
165,2024-03-02,1.558562e+09,1.609192e+09,1.549248e+09,1.590987e+09,1023948667416765
166,2024-04-01,1.774625e+09,1.818706e+09,1.774042e+09,1.817581e+09,510897986179708
167,2024-05-01,1.626628e+09,1.648641e+09,1.506379e+09,1.545027e+09,964184604657710
168,2024-05-31,1.721839e+09,1.770874e+09,1.710169e+09,1.741940e+09,751907475360969
169,2024-06-30,1.536950e+09,1.556767e+09,1.536469e+09,1.551410e+09,322395978526767
170,2024-07-30,1.739241e+09,1.783283e+09,1.695250e+09,1.702571e+09,1039091793362459
171,2024-08-29,1.516262e+09,1.534825e+09,1.475054e+09,1.504024e+09,1026578108511410
172,2024-09-28,1.660803e+09,1.693928e+09,1.652454e+09,1.676346e+09,816858566690712
173,2024-10-28,1.707758e+09,1.738279e+09,1.703267e+09,1.730839e+09,426058924733988
174,2024-11-27,2.371864e+09,2.420390e+09,2.312840e+09,2.343786e+09,2335408125916101
175,2024-12-27,2.530105e+09,2.545059e+09,2.424113e+09,2.440870e+09,1198960912650664

### Index

In [5]:
index = Vnstock().world_index(symbol='DJI', source='MSN')
df = index.quote.history(start='2023-01-01', end='2024-12-31', interval='1D')
df

          time      open      high       low     close     volume
138 2023-07-24  35230.79  35463.97  35230.79  35411.24  286173242
139 2023-07-25  35421.49  35527.57  35365.26  35438.07  309326664
140 2023-07-26  35345.99  35633.61  35306.27  35520.12  347334097
141 2023-07-27  35558.79  35645.35  35216.58  35282.72  352233629
142 2023-07-28  35443.49  35565.51  35355.15  35459.29  369000609
..         ...       ...       ...       ...       ...        ...
498 2024-12-25  42916.48  43297.65  42871.76  43297.03  -99999902
499 2024-12-26  43201.85  43373.98  43115.09  43325.80  270359363
500 2024-12-27  43142.37  43238.85  42761.56  42992.21  376962934
501 2024-12-30  42863.86  42863.86  42263.51  42573.73  383300069
502 2024-12-31  42636.70  42779.69  42421.29  42544.22  359219218

[365 rows x 6 columns]

## 3.2. Truy xuất theo id tương ứng symbol

Trong trường hợp mã symbol bạn cần không có sẵn trong danh sách được hỗ trợ, bạn có thể truy xuất dữ liệu theo id của mã đó được tìm kiếm ở mục `II. Tìm kiếm mã niêm yết được hỗ trợ bởi MSN`

In [6]:
# avyufr là symbol_id của USDEUR
from vnstock.explorer.msn.quote import *

fx = Quote(symbol_id='avyn9c')
fx.history(start='2020-01-01', end='2024-12-31')

           time  open  high   low  close
940  2023-08-09  0.91  0.91  0.91   0.91
941  2023-08-10  0.91  0.91   0.9   0.91
942  2023-08-11  0.91  0.91  0.91   0.91
943  2023-08-14  0.91  0.92  0.91   0.92
944  2023-08-15  0.92  0.92  0.91   0.92
...         ...   ...   ...   ...    ...
1300 2024-12-25  0.96  0.96  0.96   0.96
1301 2024-12-26  0.96  0.96  0.96   0.96
1302 2024-12-27  0.96  0.96  0.96   0.96
1303 2024-12-30  0.96  0.96  0.96   0.96
1304 2024-12-31  0.96  0.97  0.96   0.97

[365 rows x 5 columns]

In [7]:
# c2111 là symbol_id của BTC
crypto = Quote(symbol_id='c2111')
crypto.history(start='2023-01-01', end='2024-12-31', interval='1D')

,time,open,high,low,close,volume
151,2023-01-07,4.289933e+08,4.329560e+08,4.259344e+08,4.319362e+08,367260131016105
152,2023-02-06,5.945057e+08,5.968291e+08,5.820081e+08,5.849104e+08,498497411180750
153,2023-03-08,5.714737e+08,5.739986e+08,5.608470e+08,5.661597e+08,580063722157155
154,2023-04-07,7.179048e+08,7.179852e+08,7.067836e+08,7.145647e+08,352587383009534
155,2023-05-07,7.526501e+08,7.598168e+08,7.253893e+08,7.364898e+08,405485323884695
156,2023-06-06,6.910968e+08,6.912720e+08,6.483429e+08,6.563673e+08,548158696632310
157,2023-07-06,7.842419e+08,7.867544e+08,7.701486e+08,7.775010e+08,318031735682934
158,2023-08-05,7.433632e+08,7.466170e+08,7.359983e+08,7.408079e+08,306693586884557
159,2023-09-04,6.591542e+08,6.647006e+08,6.578180e+08,6.617046e+08,228365124845785
160,2023-10-04,7.009103e+08,7.049601e+08,6.934637e+08,6.989159e+08,290671105474313
161,2023-11-03,9.030514e+08,9.152376e+08,8.765521e+08,8.902264e+08,535033079706980
162,2023-12-03,9.858028e+08,1.011019e+09,9.848681e+08,1.005857e+09,395807227392231
163,2024-01-02,1.077300e+09,1.125590e+09,1.075638e+09,1.125384e+09,469519410734010
164,2024-02-01,1.094270e+09,1.113919e+09,1.077777e+09,1.085005e+09,628684061649716
165,2024-03-02,1.558562e+09,1.609192e+09,1.549248e+09,1.590987e+09,1023948667416765
166,2024-04-01,1.774625e+09,1.818706e+09,1.774042e+09,1.817581e+09,510897986179708
167,2024-05-01,1.626628e+09,1.648641e+09,1.506379e+09,1.545027e+09,964184604657710
168,2024-05-31,1.721839e+09,1.770874e+09,1.710169e+09,1.741940e+09,751907475360969
169,2024-06-30,1.536950e+09,1.556767e+09,1.536469e+09,1.551410e+09,322395978526767
170,2024-07-30,1.739241e+09,1.783283e+09,1.695250e+09,1.702571e+09,1039091793362459
171,2024-08-29,1.516262e+09,1.534825e+09,1.475054e+09,1.504024e+09,1026578108511410
172,2024-09-28,1.660803e+09,1.693928e+09,1.652454e+09,1.676346e+09,816858566690712
173,2024-10-28,1.707758e+09,1.738279e+09,1.703267e+09,1.730839e+09,426058924733988
174,2024-11-27,2.371864e+09,2.420390e+09,2.312840e+09,2.343786e+09,2335408125916101
175,2024-12-27,2.530105e+09,2.545059e+09,2.424113e+09,2.440870e+09,1198960912650664